export default {
  get PublicKey() {
    return "MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGFLIV0Ilj2u23zO0w2/VKi8+B6LUsRNJujl1Ozj1LPfw/ZwRWAIeHNh71YAz1d6hlnSCW8Gc3UGeqEwDHzElI30JeoHtyB4YRHNXzqFyTlshICufSLDnRLGZ5EsX6SSpHuiKnaUyrgYaBKzmAjZsKwHpvZCDDvVxBNvhlG7JeQtAgMBAAE=";
  }
};
